### PR TITLE
Use environment variable to set the cache folder and add logging if the image scan failed

### PR DESCRIPTION
**Pull request by DmitryZ-outten**
Use environment variable to set the cache folder 
Add logging if the image scan failed

### CODE REVIEW

**Comment by DmitryZ-outten** [comment]
Hi @developer-guy !
I was very happy to find that someone was already looking into how to use trivy go libs
I was trying to run it locally but it is failing right now with the following error:
`$ go run ./main.go --image alpine:3.10  --remote http://10.109.0.95:4954
2021-03-29T14:49:58.131+0300	DEBUG	Artifact ID: sha256:d1bb6234ef26de7a1976176b36eb0f518b3d3d9e6a46e2da2ae6eb0b4d99d87d
2021-03-29T14:49:58.132+0300	DEBUG	Blob IDs: [sha256:3cb2494d9fa711bd96908ce5bcf4f7e82e26df6c9ddc28c3809f7e54905dc1f2]
2021-03-29T14:49:58.203+0300	FATAL	could not scan image: scan failed: failed to detect vulnerabilities via RPC: twirp error internal: failed scan, alpine:3.10: failed to apply layers: layer cache missing: sha256:3cb2494d9fa711bd96908ce5bcf4f7e82e26df6c9ddc28c3809f7e54905dc1f2
exit status 1
`
Do you know what can be the issue? I am still learning GO and can't find what is missing =(

**Comment by developer-guy** [comment]
> Hi @developer-guy !
> I was very happy to find that someone was already looking into how to use trivy go libs
> I was trying to run it locally but it is failing right now with the following error:
> `$ go run ./main.go --image alpine:3.10 --remote http://10.109.0.95:4954 2021-03-29T14:49:58.131+0300 DEBUG Artifact ID: sha256:d1bb6234ef26de7a1976176b36eb0f518b3d3d9e6a46e2da2ae6eb0b4d99d87d 2021-03-29T14:49:58.132+0300 DEBUG Blob IDs: [sha256:3cb2494d9fa711bd96908ce5bcf4f7e82e26df6c9ddc28c3809f7e54905dc1f2] 2021-03-29T14:49:58.203+0300 FATAL could not scan image: scan failed: failed to detect vulnerabilities via RPC: twirp error internal: failed scan, alpine:3.10: failed to apply layers: layer cache missing: sha256:3cb2494d9fa711bd96908ce5bcf4f7e82e26df6c9ddc28c3809f7e54905dc1f2 exit status 1 `
> Do you know what can be the issue? I am still learning GO and can't find what is missing =(

hello @DmitryZ-outten thanks for the PR, can you try it again please, I don't understand the problem here is but when I was working with trivy, its version is 1.15.0, now he upgraded to 1.16.0, so ı updated the repo either,so, its working :/

Screen Shot 2021-03-29 at 15 33 15

**Comment by DmitryZ-outten** [comment]
@developer-guy Thanks, It works now!

**Comment by cvangeti** [comment]
Hi @developer-guy I am still getting this error. Can you please look at the error?
```
 go run ./main.go --image centos:6 --remote http://localhost:4954
hello_docker
2021-04-19T13:24:09.671-0700    DEBUG   Artifact ID: sha256:d0957ffdf8a2ea8c8925903862b65a1b6850dbb019f88d45e927d3d5a3fa0c31
2021-04-19T13:24:09.671-0700    DEBUG   Blob IDs: [sha256:af6bf1987c2eb07d73f33836b0d8fd825d7c785273526b077e46780e8b4b2ae9]
2021-04-19T13:24:09.676-0700    FATAL   could not scan image: scan failed: failed to detect vulnerabilities via RPC: twirp error internal: failed to do request: Post "http://localhost:4954/twirp/trivy.scanner.v1.Scanner/Scan": dial tcp [::1]:4954: connect: connection refused
exit status 1
```

**Comment by cvangeti** [comment]
Hi @developer-guy I am still getting this error. Could you please look at this?
```
 go run ./main.go --image centos:7 --remote http://localhost:4954
2021-04-19T13:27:10.748-0700    DEBUG   Artifact ID: sha256:8652b9f0cb4c0599575e5a003f5906876e10c1ceb2ab9fe1786712dac14a50cf
2021-04-19T13:27:10.748-0700    DEBUG   Blob IDs: [sha256:174f5685490326fc0a1c0f5570b8663732189b327007e47ff13d2ca59673db02]
2021-04-19T13:27:10.754-0700    FATAL   could not scan image: scan failed: failed to detect vulnerabilities via RPC: twirp error internal: failed scan, centos:7: failed to apply layers: layer cache missing: sha256:174f5685490326fc0a1c0f5570b8663732189b327007e47ff13d2ca59673db02
exit status 1
```

**Comment by DmitryZ-outten** [comment]
Yes. It looks like something is still missing.
I am getting the same error for any new image that I scan. 

If I run the scanning for the image manually. e.g.:
`docker run -v /var/run/docker.sock:/var/run/docker.sock --rm aquasec/trivy client --remote http://localhost:4954 centos:7 `
it returns the result and after that if I run the go binary for the same image. It works ok.

It looks like something is missing in the go script.
Maybe some cache issue?

**Pull request merged**
